# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71a69a209bffa20a725250f5ab6bb5e69d5b3c9495049577f436c76ebd13e2d9d3a413aeecbcd6bfc1e8f0a473564417d1b30442591cb688cf1cc83c495d7dfa

test:
  secret_key_base: 5e110beb3478276cbe73790b28e6cb3aaa7ec880e69801c48311fce8d45219c90f622cb981c31419f2de38305f214b63e4774bbe3568b90cf76cfe59bd4d4ffb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
